packages:
  - 'packages/*'
  - 'playground'
  - 'runtime/*'
  - 'vue-components/*'
  - 'react-components/*'
  - 'eslint-config'

catalog:
  vue: ^3.5.17
  '@vue/compiler-sfc': ^3.5.17
  vite: ^7.0.0
  typescript: "^5.8.3"
  